// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{0}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type PageRequest struct {
	PageNumber           uint32   `protobuf:"varint,1,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize             uint32   `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageRequest) Reset()         { *m = PageRequest{} }
func (m *PageRequest) String() string { return proto.CompactTextString(m) }
func (*PageRequest) ProtoMessage()    {}
func (*PageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{1}
}

func (m *PageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageRequest.Unmarshal(m, b)
}
func (m *PageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageRequest.Marshal(b, m, deterministic)
}
func (m *PageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageRequest.Merge(m, src)
}
func (m *PageRequest) XXX_Size() int {
	return xxx_messageInfo_PageRequest.Size(m)
}
func (m *PageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PageRequest proto.InternalMessageInfo

func (m *PageRequest) GetPageNumber() uint32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *PageRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ProductResponseList struct {
	Products             []*ProductResponse `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProductResponseList) Reset()         { *m = ProductResponseList{} }
func (m *ProductResponseList) String() string { return proto.CompactTextString(m) }
func (*ProductResponseList) ProtoMessage()    {}
func (*ProductResponseList) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{2}
}

func (m *ProductResponseList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductResponseList.Unmarshal(m, b)
}
func (m *ProductResponseList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductResponseList.Marshal(b, m, deterministic)
}
func (m *ProductResponseList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductResponseList.Merge(m, src)
}
func (m *ProductResponseList) XXX_Size() int {
	return xxx_messageInfo_ProductResponseList.Size(m)
}
func (m *ProductResponseList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductResponseList.DiscardUnknown(m)
}

var xxx_messageInfo_ProductResponseList proto.InternalMessageInfo

func (m *ProductResponseList) GetProducts() []*ProductResponse {
	if m != nil {
		return m.Products
	}
	return nil
}

type ProductRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price                uint32   `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Count                uint32   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductRequest) Reset()         { *m = ProductRequest{} }
func (m *ProductRequest) String() string { return proto.CompactTextString(m) }
func (*ProductRequest) ProtoMessage()    {}
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{3}
}

func (m *ProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductRequest.Unmarshal(m, b)
}
func (m *ProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductRequest.Marshal(b, m, deterministic)
}
func (m *ProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductRequest.Merge(m, src)
}
func (m *ProductRequest) XXX_Size() int {
	return xxx_messageInfo_ProductRequest.Size(m)
}
func (m *ProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductRequest proto.InternalMessageInfo

func (m *ProductRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductRequest) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ProductRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ProductModel struct {
	ID                   uint32               `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                uint32               `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Count                uint32               `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProductModel) Reset()         { *m = ProductModel{} }
func (m *ProductModel) String() string { return proto.CompactTextString(m) }
func (*ProductModel) ProtoMessage()    {}
func (*ProductModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{4}
}

func (m *ProductModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductModel.Unmarshal(m, b)
}
func (m *ProductModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductModel.Marshal(b, m, deterministic)
}
func (m *ProductModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductModel.Merge(m, src)
}
func (m *ProductModel) XXX_Size() int {
	return xxx_messageInfo_ProductModel.Size(m)
}
func (m *ProductModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductModel.DiscardUnknown(m)
}

var xxx_messageInfo_ProductModel proto.InternalMessageInfo

func (m *ProductModel) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ProductModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductModel) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ProductModel) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ProductModel) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ProductModel) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *ProductModel) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type ProductResponse struct {
	ID                   int32                `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                int32                `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Count                int32                `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProductResponse) Reset()         { *m = ProductResponse{} }
func (m *ProductResponse) String() string { return proto.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()    {}
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{5}
}

func (m *ProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductResponse.Unmarshal(m, b)
}
func (m *ProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductResponse.Marshal(b, m, deterministic)
}
func (m *ProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductResponse.Merge(m, src)
}
func (m *ProductResponse) XXX_Size() int {
	return xxx_messageInfo_ProductResponse.Size(m)
}
func (m *ProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductResponse proto.InternalMessageInfo

func (m *ProductResponse) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ProductResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductResponse) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ProductResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ProductResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ProductResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type UpdateProductRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                uint32   `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Count                uint32   `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductRequest) Reset()         { *m = UpdateProductRequest{} }
func (m *UpdateProductRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductRequest) ProtoMessage()    {}
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{6}
}

func (m *UpdateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductRequest.Unmarshal(m, b)
}
func (m *UpdateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductRequest.Merge(m, src)
}
func (m *UpdateProductRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductRequest.Size(m)
}
func (m *UpdateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductRequest proto.InternalMessageInfo

func (m *UpdateProductRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateProductRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProductRequest) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *UpdateProductRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ID struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{7}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func init() {
	proto.RegisterType((*EmptyResponse)(nil), "pb.EmptyResponse")
	proto.RegisterType((*PageRequest)(nil), "pb.PageRequest")
	proto.RegisterType((*ProductResponseList)(nil), "pb.ProductResponseList")
	proto.RegisterType((*ProductRequest)(nil), "pb.ProductRequest")
	proto.RegisterType((*ProductModel)(nil), "pb.ProductModel")
	proto.RegisterType((*ProductResponse)(nil), "pb.ProductResponse")
	proto.RegisterType((*UpdateProductRequest)(nil), "pb.UpdateProductRequest")
	proto.RegisterType((*ID)(nil), "pb.ID")
}

func init() {
	proto.RegisterFile("proto/product.proto", fileDescriptor_cfd9ed8e6077aee0)
}

var fileDescriptor_cfd9ed8e6077aee0 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x6d, 0xd2, 0x4d, 0xd9, 0x9d, 0xd2, 0x96, 0xba, 0x95, 0x88, 0x72, 0x80, 0xca, 0xa7, 0x9e,
	0x12, 0x54, 0x2e, 0x70, 0x41, 0xda, 0x12, 0x40, 0x91, 0x00, 0x55, 0x59, 0xb8, 0x70, 0x41, 0x49,
	0x33, 0x5b, 0x45, 0x6a, 0x1a, 0x93, 0x38, 0x48, 0xcb, 0x4f, 0xf0, 0x2d, 0x7c, 0x0d, 0xbf, 0x83,
	0xec, 0x38, 0xa1, 0x8d, 0x2c, 0x15, 0x89, 0xc3, 0xde, 0x32, 0x93, 0xf7, 0x3c, 0xcf, 0xf3, 0xc6,
	0x03, 0x33, 0x56, 0xe4, 0x3c, 0xf7, 0x58, 0x91, 0x27, 0xd5, 0x96, 0xbb, 0x32, 0x22, 0x26, 0x8b,
	0x9d, 0xa7, 0xbb, 0x3c, 0xdf, 0xed, 0xd1, 0x93, 0x99, 0xb8, 0xba, 0xf5, 0x78, 0x9a, 0x61, 0xc9,
	0xa3, 0x8c, 0xd5, 0x20, 0x3a, 0x81, 0xd1, 0x9b, 0x8c, 0xf1, 0xbb, 0x10, 0x4b, 0x96, 0x1f, 0x4a,
	0xa4, 0x01, 0x0c, 0x37, 0xd1, 0x0e, 0x43, 0xfc, 0x56, 0x61, 0xc9, 0xc9, 0x13, 0x00, 0x16, 0xed,
	0xf0, 0x63, 0x95, 0xc5, 0x58, 0xd8, 0xc6, 0xc2, 0x58, 0x8e, 0xc2, 0xa3, 0x0c, 0x71, 0xe0, 0x52,
	0x44, 0x37, 0xe9, 0x0f, 0xb4, 0x4d, 0xf9, 0xb7, 0x8d, 0xe9, 0x5b, 0x98, 0x6d, 0x6a, 0x45, 0xcd,
	0xe9, 0xef, 0xd3, 0x92, 0x13, 0x0f, 0x2e, 0x95, 0xd0, 0xd2, 0x36, 0x16, 0xfd, 0xe5, 0x70, 0x35,
	0x73, 0x59, 0xec, 0x76, 0xa0, 0x61, 0x0b, 0xa2, 0x1b, 0x18, 0xb7, 0x3f, 0x6b, 0x55, 0x04, 0x2e,
	0x0e, 0x51, 0x86, 0x52, 0xcf, 0x55, 0x28, 0xbf, 0xc9, 0x1c, 0x2c, 0x56, 0xa4, 0xdb, 0x46, 0x46,
	0x1d, 0x88, 0xec, 0x36, 0xaf, 0x0e, 0xdc, 0xee, 0xd7, 0x59, 0x19, 0xd0, 0x9f, 0x26, 0x3c, 0x54,
	0x47, 0x7e, 0xc8, 0x13, 0xdc, 0x93, 0x31, 0x98, 0x81, 0xaf, 0xae, 0x67, 0x06, 0x7e, 0x5b, 0xc0,
	0xd4, 0x15, 0xe8, 0x6b, 0x0b, 0x5c, 0x1c, 0x15, 0x20, 0x2f, 0x01, 0xb6, 0x05, 0x46, 0x1c, 0x93,
	0xaf, 0x11, 0xb7, 0xad, 0x85, 0xb1, 0x1c, 0xae, 0x1c, 0xb7, 0x36, 0xc3, 0x6d, 0xcc, 0x70, 0x3f,
	0x35, 0x66, 0x84, 0x57, 0x0a, 0x7d, 0x2d, 0xa9, 0x15, 0x4b, 0x1a, 0xea, 0xe0, 0x3c, 0x55, 0xa1,
	0x6b, 0x6a, 0x82, 0x7b, 0x54, 0xd4, 0x07, 0xe7, 0xa9, 0x0a, 0x7d, 0xcd, 0xe9, 0x6f, 0x03, 0x26,
	0x1d, 0x07, 0x8e, 0x9a, 0x62, 0xfd, 0x5b, 0x53, 0x2c, 0x6d, 0x53, 0xac, 0x7b, 0x6d, 0x0a, 0xbd,
	0x85, 0xf9, 0x67, 0x19, 0x74, 0x66, 0x68, 0x0c, 0x66, 0x9a, 0x34, 0x96, 0xa7, 0xc9, 0xff, 0x5a,
	0x4e, 0xe7, 0xa2, 0x5b, 0xdd, 0x41, 0x5a, 0xfd, 0x32, 0xdb, 0xe1, 0xbd, 0xc1, 0xe2, 0xbb, 0xa0,
	0xbf, 0x80, 0xd1, 0x6b, 0x79, 0x31, 0x95, 0x27, 0xe4, 0x64, 0xfc, 0xa5, 0x3a, 0x67, 0x2a, 0x72,
	0xa7, 0x2f, 0xb3, 0x47, 0x3c, 0x18, 0xbf, 0x43, 0xae, 0x90, 0xeb, 0xbb, 0xc0, 0x27, 0x03, 0x01,
	0x0b, 0x7c, 0x47, 0xf7, 0x82, 0x68, 0x8f, 0xac, 0x61, 0x7a, 0x72, 0x77, 0xc9, 0xb1, 0x05, 0x56,
	0xd7, 0x12, 0x7d, 0xd1, 0x67, 0x30, 0xf5, 0xe5, 0x98, 0xe8, 0xea, 0x6a, 0x19, 0xaf, 0xe0, 0xd1,
	0xb1, 0x4c, 0xb1, 0x4e, 0xc8, 0x44, 0x0a, 0xfc, 0xbb, 0x58, 0x9c, 0xc7, 0x1a, 0xc5, 0x62, 0x3d,
	0xd0, 0xde, 0xda, 0xfa, 0xd2, 0xf7, 0x58, 0x1c, 0x0f, 0xa4, 0xaf, 0xcf, 0xff, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x46, 0x8f, 0x0d, 0x6c, 0xdd, 0x04, 0x00, 0x00,
}
